# Generated by Django 3.1.3 on 2021-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='directory',
            field=models.CharField(default='NOT PROVIDED', max_length=1000),
        ),
        migrations.AddField(
            model_name='method',
            name='directory',
            field=models.CharField(default='NOT PROVIDED', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='directory',
            field=models.CharField(default='NOT PROVIDED', max_length=1000),
        ),
    ]
