# Generated by Django 3.1.3 on 2021-03-31 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20210331_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='documentation.project'),
        ),
        migrations.AlterField(
            model_name='method',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='documentation.interface'),
        ),
    ]
