# Generated by Django 3.1.3 on 2021-04-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20210331_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='prints',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
